### ISSUE TITLE
Jupyter Notebooks do not work out of the box

### ISSUE THREAD

**Issue by maximilian-galanis** [StatisKit/FP17#5]
When following the installation instructions in the README file, the necessary libraries or modules (e.g., libbasic) are not being built. This is the output I get when trying to execute the first part of index.ipynb:

```
jupyter notebook ./share/jupyter/index.ipynb 
[...]
[NbConvertApp] Converting notebook basic.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - libbasic



CommandNotFoundError: To use 'conda build', install conda-build.

[NbConvertApp] ERROR | Error while converting 'basic.ipynb'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 138, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 315, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 354, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/user/miniconda3/envs/fp17/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 378, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
subprocess.call('conda remove -y libbasic', shell=True)
CONDA_RECIPE = os.path.join(GIT_ROOT, 'bin', 'conda', 'libbasic')
subprocess.check_call('conda build --python=' + PYTHON_VERSION + ' ' + CONDA_RECIPE + ' -c statiskit -c defaults --override-channels',
                      shell=True)
subprocess.check_call('conda install -y libbasic --use-local -c statiskit -c defaults --override-channels',
                      shell=True)
------------------

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-7-059b9ae9f86d> in <module>
      2 CONDA_RECIPE = os.path.join(GIT_ROOT, 'bin', 'conda', 'libbasic')
      3 subprocess.check_call('conda build --python=' + PYTHON_VERSION + ' ' + CONDA_RECIPE + ' -c statiskit -c defaults --override-channels',
----> 4                       shell=True)
      5 subprocess.check_call('conda install -y libbasic --use-local -c statiskit -c defaults --override-channels',
      6                       shell=True)

~/miniconda3/envs/fp17/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    345         if cmd is None:
    346             cmd = popenargs[0]
--> 347         raise CalledProcessError(retcode, cmd)
    348     return 0
    349 

CalledProcessError: Command 'conda build --python=3.7 /home/user/Documents/Projects/Python/AutoWIG-FP17/FP17/bin/conda/libbasic -c statiskit -c defaults --override-channels' returned non-zero exit status 1.
CalledProcessError: Command 'conda build --python=3.7 /home/user/Documents/Projects/Python/AutoWIG-FP17/FP17/bin/conda/libbasic -c statiskit -c defaults --override-channels' returned non-zero exit status 1.
```

Some quick info on how to build it (I guess I have to use scons?) would be very helpful.
Maybe the conda build package is missing in the provided meta package?

This is my environment:
[environment.txt](https://github.com/StatisKit/FP17/files/3043527/environment.txt)

**Comment by pfernique** [comment]
Did you install `conda-build` in your `base` environment ?

```console
conda install -n base conda-build
```

This is required but since you can only install it in the `base` environment, this has to be done manually.
I will add it to the documentation.

**Comment by pfernique** [comment]
Note that I'm not sure that the install documentation of FP17 is up to date.
Using the `autowig-toolchain` environment with `jupyter` installed, should be enough.

**Comment by maximilian-galanis** [comment]
I just installed conda-build. But the libbasic package still cannot be build.
I think the cause of the error lies here:
```
subprocess.call('conda remove -y libbasic', shell=True)
CONDA_RECIPE = os.path.join(GIT_ROOT, 'bin', 'conda', 'libbasic')
subprocess.check_call('conda build --python=' + PYTHON_VERSION + ' ' + CONDA_RECIPE + ' -c statiskit -c defaults --override-channels',
                      shell=True)
subprocess.check_call('conda install -y libbasic --use-local -c statiskit -c defaults --override-channels',
                      shell=True)
```
_CONDA_RECIPE_ does not point to a valid directory. There is no bin folder in the Git repository and thus _conda_ cannot build anything.

**Comment by pfernique** [comment]
Well, l wanted to update notebooks for a long time but didn't have time. Today (as you can see) and tomorow I have some. I will try to repair all notebooks.

The major problems are that:

*  the repository structure have been changed.
* the **PyBind11** generator has been implemented and files related to `SCons` are ot up-to-date with the new version of `scons-tools`.

Note that this will take a little time (at least to replay all notebooks). I will let you know when all notebooks are ready.

**Comment by maximilian-galanis** [comment]
Thank you so much!

**Comment by pfernique** [comment]
Hy, it's been a while but I was working on other projects.
I just committed few changes that repair three out of four notebooks.
The only one not working is the one with dependent libraries.
This is due to the fact that repositories for libraries used are now missing.
I will transform this notebook in a little time but you can play with the others.
Note that this requires to update the `fp17` environment (using **AutoWIG** 1.1.0)
